# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pending.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PendingDialog(object):
    def setupUi(self, PendingDialog):
        PendingDialog.setObjectName("PendingDialog")
        PendingDialog.resize(526, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(PendingDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tab_widget = QtWidgets.QTabWidget(PendingDialog)
        self.tab_widget.setObjectName("tab_widget")
        self.loans_tab = QtWidgets.QWidget()
        self.loans_tab.setObjectName("loans_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.loans_tab)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.loans_table = QtWidgets.QTableWidget(self.loans_tab)
        self.loans_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.loans_table.setObjectName("loans_table")
        self.loans_table.setColumnCount(4)
        self.loans_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.loans_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.loans_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.loans_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.loans_table.setHorizontalHeaderItem(3, item)
        self.verticalLayout_2.addWidget(self.loans_table)
        self.tab_widget.addTab(self.loans_tab, "")
        self.debts_tab = QtWidgets.QWidget()
        self.debts_tab.setObjectName("debts_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.debts_tab)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.debts_table = QtWidgets.QTableWidget(self.debts_tab)
        self.debts_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.debts_table.setObjectName("debts_table")
        self.debts_table.setColumnCount(4)
        self.debts_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.debts_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.debts_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.debts_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.debts_table.setHorizontalHeaderItem(3, item)
        self.verticalLayout_3.addWidget(self.debts_table)
        self.tab_widget.addTab(self.debts_tab, "")
        self.verticalLayout.addWidget(self.tab_widget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.select_all_button = QtWidgets.QPushButton(PendingDialog)
        self.select_all_button.setObjectName("select_all_button")
        self.horizontalLayout.addWidget(self.select_all_button)
        self.select_none_button = QtWidgets.QPushButton(PendingDialog)
        self.select_none_button.setObjectName("select_none_button")
        self.horizontalLayout.addWidget(self.select_none_button)
        self.button_box = QtWidgets.QDialogButtonBox(PendingDialog)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setCenterButtons(False)
        self.button_box.setObjectName("button_box")
        self.horizontalLayout.addWidget(self.button_box)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(PendingDialog)
        self.tab_widget.setCurrentIndex(0)
        self.button_box.accepted.connect(PendingDialog.accept)
        self.button_box.rejected.connect(PendingDialog.reject)
        self.select_none_button.clicked.connect(PendingDialog.select_none)
        self.select_all_button.clicked.connect(PendingDialog.select_all)
        QtCore.QMetaObject.connectSlotsByName(PendingDialog)

    def retranslateUi(self, PendingDialog):
        _translate = QtCore.QCoreApplication.translate
        PendingDialog.setWindowTitle(_translate("PendingDialog", "Dialog"))
        item = self.loans_table.horizontalHeaderItem(0)
        item.setText(_translate("PendingDialog", "UOMe ID"))
        item = self.loans_table.horizontalHeaderItem(1)
        item.setText(_translate("PendingDialog", "Borrower"))
        item = self.loans_table.horizontalHeaderItem(2)
        item.setText(_translate("PendingDialog", "Amount"))
        item = self.loans_table.horizontalHeaderItem(3)
        item.setText(_translate("PendingDialog", "Description"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.loans_tab), _translate("PendingDialog", "Loans"))
        item = self.debts_table.horizontalHeaderItem(0)
        item.setText(_translate("PendingDialog", "UOMe ID"))
        item = self.debts_table.horizontalHeaderItem(1)
        item.setText(_translate("PendingDialog", "Loaner"))
        item = self.debts_table.horizontalHeaderItem(2)
        item.setText(_translate("PendingDialog", "Amount"))
        item = self.debts_table.horizontalHeaderItem(3)
        item.setText(_translate("PendingDialog", "Description"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.debts_tab), _translate("PendingDialog", "Debts"))
        self.select_all_button.setText(_translate("PendingDialog", "Select All"))
        self.select_none_button.setText(_translate("PendingDialog", "Select None"))

