# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_server_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='user',
            name='confirmed1',
            field=models.BooleanField(default=False),
        ),
    ]
