# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_server_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmedinvitation',
            name='uuid',
        ),
        migrations.AddField(
            model_name='invitation',
            name='signature_group',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='invitation',
            name='signature_invitee',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.DeleteModel(
            name='ConfirmedInvitation',
        ),
    ]
