# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_server_app', '0002_auto_20170102_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmed1',
        ),
        migrations.AddField(
            model_name='user',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
